# Generated by Django 5.2.13 on 2026-07-22 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='username_actualizado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
