# Generated by Django 5.2.13 on 2026-08-21 04:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
        ('ubicaciones', '0003_poblar_capital_superficie_altitud'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagExperiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('icono_bootstrap', models.CharField(blank=True, help_text='Ejemplo: bi-people-fill, bi-camera-fill, bi-tree-fill', max_length=80)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tag de experiencia',
                'verbose_name_plural': 'Tags de experiencia',
                'ordering': ['nombre'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='evento',
            name='unique_evento_nombre_fecha_inicio',
        ),
        migrations.AddField(
            model_name='evento',
            name='anio_aproximado',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='contexto_cultural',
            field=models.TextField(blank=True, help_text='Significado, tradición o contexto cultural. Se omite en el sitio si queda vacío.', verbose_name='¿Qué debes saber?'),
        ),
        migrations.AddField(
            model_name='evento',
            name='descripcion_ubicacion',
            field=models.CharField(blank=True, help_text='Ejemplo: Diversos puntos de la ciudad de Huánuco. Solo para itinerante/varios lugares.', max_length=255),
        ),
        migrations.AddField(
            model_name='evento',
            name='dia_fin_anual',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AddField(
            model_name='evento',
            name='dia_inicio_anual',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AddField(
            model_name='evento',
            name='estado',
            field=models.CharField(choices=[('programado', 'Programado'), ('reprogramado', 'Reprogramado'), ('cancelado', 'Cancelado')], default='programado', max_length=20),
        ),
        migrations.AddField(
            model_name='evento',
            name='fecha_verificacion',
            field=models.DateField(blank=True, help_text='Última revisión del dato. Uso interno.', null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='mes_aproximado',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='mes_fin_anual',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='mes_inicio_anual',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='provincia',
            field=models.ForeignKey(blank=True, help_text='Usar solo si el evento NO tiene un distrito único identificable (se deriva del distrito si este está indicado).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='ubicaciones.provincia'),
        ),
        migrations.AddField(
            model_name='evento',
            name='tipo_fecha',
            field=models.CharField(choices=[('exacta', 'Fecha exacta (un solo día)'), ('rango', 'Rango de fechas'), ('anual_fija', 'Fecha anual fija (se repite cada año)'), ('mes_aproximado', 'Mes aproximado'), ('por_confirmar', 'Fecha por confirmar')], default='exacta', max_length=20),
        ),
        migrations.AddField(
            model_name='evento',
            name='tipo_horario',
            field=models.CharField(choices=[('exacta', 'Hora exacta'), ('rango', 'Rango de horas'), ('todo_el_dia', 'Todo el día'), ('variable', 'Horarios variables'), ('por_confirmar', 'Horario por confirmar'), ('no_aplica', 'No aplica')], default='exacta', max_length=20),
        ),
        migrations.AddField(
            model_name='evento',
            name='tipo_ubicacion',
            field=models.CharField(choices=[('lugar_exacto', 'Lugar exacto'), ('varios_lugares', 'Varios lugares'), ('itinerante', 'Itinerante'), ('ambito_general', 'Ámbito general')], default='lugar_exacto', max_length=20),
        ),
        migrations.AddField(
            model_name='evento',
            name='url_fuente',
            field=models.URLField(blank=True, help_text='Enlace usado para verificar esta información. Uso interno.'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='notas',
            field=models.TextField(blank=True, help_text='Uso exclusivo del equipo editor. No se muestra al turista.'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='publico_objetivo',
            field=models.CharField(blank=True, help_text='Campo legado: ya no alimenta filtros ni "Ideal para" (usar Tags de experiencia). Ejemplo: público general, familias, niños, turistas, jóvenes.', max_length=160),
        ),
        migrations.AlterField(
            model_name='evento',
            name='tipo_costo',
            field=models.CharField(choices=[('gratis', 'Gratis'), ('pagado', 'Pagado'), ('consultar', 'Consultar'), ('no_aplica', 'No aplica')], default='consultar', max_length=20),
        ),
        migrations.AddField(
            model_name='evento',
            name='tags_experiencia',
            field=models.ManyToManyField(blank=True, related_name='eventos', to='eventos.tagexperiencia', verbose_name='Ideal para'),
        ),
    ]
