# Generated by Django 5.2.13 on 2026-08-21 20:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_tagexperiencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='dia_ancla_relativa',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Vacío = N-ésimo día de semana del mes. Con valor = PRIMER día de semana posterior a esa fecha (mismo mes que 'mes_relativa'). Con ancla, el orden debe ser 'Primer'.", null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AddField(
            model_name='evento',
            name='dia_semana_relativa',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='mes_relativa',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='offset_dias_pascua',
            field=models.SmallIntegerField(blank=True, choices=[(-7, 'Domingo de Ramos'), (-3, 'Jueves Santo'), (-2, 'Viernes Santo'), (0, 'Domingo de Resurrección')], null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='orden_semana_relativa',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Primer'), (2, 'Segundo'), (3, 'Tercer'), (4, 'Cuarto')], null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='tipo_fecha',
            field=models.CharField(choices=[('exacta', 'Fecha exacta (un solo día)'), ('rango', 'Rango de fechas'), ('anual_fija', 'Fecha anual fija (se repite cada año)'), ('anual_relativa', 'Día de semana relativo (ej. 2do domingo de un mes)'), ('pascua_relativa', 'Fecha móvil relativa a Pascua'), ('mes_aproximado', 'Mes aproximado'), ('por_confirmar', 'Fecha por confirmar')], default='exacta', max_length=20),
        ),
    ]
