# Generated by Django 5.2.13 on 2026-09-02 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_evento_dia_ancla_relativa_evento_dia_semana_relativa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecomendacionEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título corto del consejo. Ejemplo: Llega con anticipación.', max_length=140)),
                ('descripcion', models.TextField(help_text='Detalle breve de la recomendación. Evita textos largos; idealmente 1 o 2 líneas.')),
                ('icono_bootstrap', models.CharField(blank=True, default='bi bi-lightbulb', help_text='Ejemplo: bi bi-shield-check, bi bi-camera, bi bi-cup-hot', max_length=80)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendaciones_detalle', to='eventos.evento')),
            ],
            options={
                'verbose_name': 'Recomendación de evento',
                'verbose_name_plural': 'Recomendaciones de eventos',
                'ordering': ['evento__nombre', 'orden', 'id'],
            },
        ),
    ]
