# Generated by Django 5.2.13 on 2026-09-03 17:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_recomendacionevento'),
    ]

    operations = [
        migrations.AddField(
            model_name='recomendacionevento',
            name='icono_archivo',
            field=models.CharField(blank=True, help_text='Nombre del archivo SVG en static/assets/img/eventos/ (no la ruta completa). Ejemplo: reco-programacion.svg. Si se deja vacío, se usa el icono de Bootstrap.', max_length=120, validators=[django.core.validators.RegexValidator(message='Usa solo el nombre del archivo SVG (sin rutas ni URLs), ej. reco-programacion.svg.', regex='^[\\w-]+\\.svg$')], verbose_name='Icono SVG'),
        ),
        migrations.AlterField(
            model_name='recomendacionevento',
            name='icono_bootstrap',
            field=models.CharField(blank=True, default='bi bi-lightbulb', help_text='Ejemplo: bi bi-shield-check, bi bi-camera, bi bi-cup-hot', max_length=80, verbose_name='Icono Bootstrap (fallback)'),
        ),
    ]
