# Generated by Django 5.2.13 on 2026-08-18 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubicaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='provincia',
            name='altitud_m',
            field=models.PositiveIntegerField(blank=True, help_text='Altitud de la capital provincial, en msnm.', null=True),
        ),
        migrations.AddField(
            model_name='provincia',
            name='capital',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='provincia',
            name='superficie_km2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
