# Generated by Django 5.2.13 on 2026-05-22 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimientos', '0004_alter_establecimiento_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='establecimiento',
            name='carta_pdf',
            field=models.FileField(blank=True, help_text='Opcional. Para restaurantes: sube la carta en formato PDF. Se abrirá en una nueva pestaña.', upload_to='establecimientos/cartas/', verbose_name='Carta en PDF'),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='carta_url',
            field=models.URLField(blank=True, help_text='Opcional. Úsalo si la carta está publicada en una URL externa.', verbose_name='URL de carta externa'),
        ),
        migrations.CreateModel(
            name='RecomendacionEstablecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ejemplo restaurante: Pachamanca. Ejemplo alojamiento: Habitación individual.', max_length=140)),
                ('imagen', models.ImageField(blank=True, help_text='Opcional. En restaurantes puede usarse para la imagen del plato. En alojamientos no se mostrará en el detalle público.', upload_to='establecimientos/recomendaciones/')),
                ('orden', models.PositiveSmallIntegerField(default=1, help_text='Orden de visualización. Usar 1, 2 o 3.')),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendaciones', to='establecimientos.establecimiento')),
            ],
            options={
                'verbose_name': 'Recomendación de establecimiento',
                'verbose_name_plural': 'Recomendaciones de establecimientos',
                'ordering': ['establecimiento__nombre', 'orden', 'id'],
                'constraints': [models.UniqueConstraint(fields=('establecimiento', 'orden'), name='unique_recomendacion_orden_por_establecimiento')],
            },
        ),
    ]
