# Generated by Django 5.2.13 on 2026-05-23 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimientos', '0005_establecimiento_carta_pdf_establecimiento_carta_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recomendacionestablecimiento',
            name='icono_archivo',
            field=models.FileField(blank=True, help_text='Opcional. Para alojamientos: sube un ícono SVG, PNG, JPG o WebP para esta recomendación.', upload_to='establecimientos/recomendaciones/iconos/', verbose_name='Ícono para alojamiento'),
        ),
    ]
