# Generated by Django 5.2.13 on 2026-05-24 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimientos', '0006_recomendacionestablecimiento_icono_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursalestablecimiento',
            name='embed_maps',
            field=models.TextField(blank=True, help_text="Pega aquí el código &lt;iframe&gt; completo que te da Google Maps en 'Compartir → Insertar un mapa'. Muestra el pin con el nombre real del establecimiento. Déjalo vacío si el local no aparece en Google Maps.", verbose_name='Código embed de Google Maps'),
        ),
        migrations.AddField(
            model_name='sucursalestablecimiento',
            name='maps_url',
            field=models.URLField(blank=True, help_text="Pega aquí la URL de la ficha del negocio en Google Maps (la dirección que ves en el navegador al abrir el lugar). Se usa para los botones 'Abrir mapa' y 'Cómo llegar' apuntando exactamente a la ficha del establecimiento. Déjalo vacío si el local no aparece en Google Maps.", verbose_name='URL de la ficha en Google Maps'),
        ),
    ]
