# Generated by Django 5.2.13 on 2026-05-25 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimientos', '0007_sucursalestablecimiento_embed_maps_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursalestablecimiento',
            name='maps_url',
            field=models.TextField(blank=True, help_text="Pega aquí la URL de la ficha del negocio en Google Maps (la dirección que ves en el navegador al abrir el lugar). Se usa para los botones 'Abrir mapa' y 'Cómo llegar' apuntando exactamente a la ficha del establecimiento. Déjalo vacío si el local no aparece en Google Maps.", verbose_name='URL de la ficha en Google Maps'),
        ),
    ]
