# Generated by Django 5.2.13 on 2026-08-17 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimientos', '0008_alter_sucursalestablecimiento_maps_url'),
        ('gastronomia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recomendacionestablecimiento',
            name='plato_tipico',
            field=models.ForeignKey(blank=True, help_text='Opcional. Vincula esta recomendación con un plato del catálogo de Platos típicos.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recomendaciones', to='gastronomia.platotipico', verbose_name='Plato típico relacionado'),
        ),
    ]
