# Generated by Django 5.2.13 on 2026-05-28 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True, unique=True, verbose_name='Fecha')),
                ('moneda_origen', models.CharField(default='USD', max_length=3, verbose_name='Moneda origen')),
                ('moneda_destino', models.CharField(default='PEN', max_length=3, verbose_name='Moneda destino')),
                ('compra', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Precio compra')),
                ('venta', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Precio venta')),
                ('fuente', models.CharField(default='SUNAT/SBS - Decolecta', max_length=120, verbose_name='Fuente')),
                ('respuesta_api', models.JSONField(blank=True, null=True, verbose_name='Respuesta API')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
            ],
            options={
                'verbose_name': 'Tipo de cambio',
                'verbose_name_plural': 'Tipos de cambio',
                'ordering': ['-fecha', '-actualizado_en'],
            },
        ),
    ]
