# Generated by Django 5.2.13 on 2026-08-03 17:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ubicaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZonaAtencionEmergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_publico', models.CharField(blank=True, help_text='Denominación reconocible para el turista, si difiere del nombre oficial del distrito.', max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('distrito', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='zona_emergencia', to='ubicaciones.distrito')),
            ],
            options={
                'verbose_name': 'Zona de atención de emergencia',
                'verbose_name_plural': 'Zonas de atención de emergencia',
                'ordering': ['orden', 'nombre_publico', 'distrito__nombre_oficial'],
            },
        ),
        migrations.CreateModel(
            name='ContactoEmergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ambito', models.CharField(choices=[('nacional', 'Nacional'), ('local', 'Local')], db_index=True, max_length=20)),
                ('categoria', models.CharField(choices=[('policia', 'Policía'), ('bomberos', 'Bomberos'), ('salud', 'Salud'), ('turismo', 'Policía de Turismo'), ('serenazgo', 'Serenazgo'), ('municipal', 'Municipal'), ('otro', 'Otro')], max_length=30)),
                ('nombre', models.CharField(max_length=160)),
                ('descripcion', models.CharField(blank=True, max_length=240)),
                ('numero_visible', models.CharField(help_text='Formato para mostrar en pantalla. Admite espacios, paréntesis o guiones.', max_length=40)),
                ('numero_tel', models.CharField(help_text='Formato normalizado para href="tel:...". Solo dígitos y \'+\' inicial opcional.', max_length=30, validators=[django.core.validators.RegexValidator(message="Usa solo dígitos y, opcionalmente, un '+' inicial (formato compatible con enlaces tel:).", regex='^\\+?\\d+$')])),
                ('es_24_horas', models.BooleanField(default=False)),
                ('horario', models.CharField(blank=True, help_text="Se usa solo cuando 'Atiende 24 horas' está desactivado.", max_length=160)),
                ('fuente_nombre', models.CharField(blank=True, max_length=180)),
                ('fuente_url', models.URLField(blank=True)),
                ('fecha_verificacion', models.DateField(blank=True, null=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('zonas', models.ManyToManyField(blank=True, related_name='contactos', to='emergencias.zonaatencionemergencia')),
            ],
            options={
                'verbose_name': 'Contacto de emergencia',
                'verbose_name_plural': 'Contactos de emergencia',
                'ordering': ['orden', 'nombre'],
            },
        ),
    ]
