# Generated by Django 5.2.13 on 2026-08-04 22:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactoemergencia',
            name='color_marca',
            field=models.CharField(blank=True, help_text='Color representativo de la institución (ej. #D64545). Si se deja vacío, se usa un color por defecto según la categoría.', max_length=7, validators=[django.core.validators.RegexValidator(message='Usa un color hexadecimal de 6 dígitos, ej. #D64545.', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
        migrations.AddField(
            model_name='contactoemergencia',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo o emblema de la institución, mostrado en la esquina superior de la tarjeta.', upload_to='emergencias/logos/'),
        ),
    ]
