# Generated by Django 5.2.13 on 2026-08-07 20:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencias', '0002_contactoemergencia_color_marca_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumeroContactoAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiqueta', models.CharField(blank=True, help_text='Ej. Móvil, Central, WhatsApp. Opcional.', max_length=40)),
                ('numero_visible', models.CharField(help_text='Formato para mostrar en pantalla. Admite espacios, paréntesis o guiones.', max_length=40)),
                ('numero_tel', models.CharField(help_text='Formato normalizado para href="tel:...". Solo dígitos y \'+\' inicial opcional.', max_length=30, validators=[django.core.validators.RegexValidator(message="Usa solo dígitos y, opcionalmente, un '+' inicial (formato compatible con enlaces tel:).", regex='^\\+?\\d+$')])),
                ('orden', models.PositiveIntegerField(default=0)),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numeros_adicionales', to='emergencias.contactoemergencia')),
            ],
            options={
                'verbose_name': 'Número adicional de contacto',
                'verbose_name_plural': 'Números adicionales de contacto',
                'ordering': ['orden', 'id'],
            },
        ),
    ]
