# Generated by Django 5.2.13 on 2026-05-25 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turismo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lugarturistico',
            name='embed_maps',
            field=models.TextField(blank=True, help_text='Pega el código iframe completo de Google Maps o solo la URL src. Se usa para el mapa visual (gratuito, sin API key).'),
        ),
        migrations.AddField(
            model_name='lugarturistico',
            name='maps_url',
            field=models.TextField(blank=True, help_text='URL larga de la ficha del lugar en Google Maps. Conservar las coordenadas !3d y !4d para generar la ruta precisa en Cómo llegar.'),
        ),
    ]
