# Generated by Django 5.2.13 on 2026-07-02 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turismo', '0005_imagenlugarturistico_video_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lugarturistico',
            name='tipo_costo',
            field=models.CharField(choices=[('no_requiere', 'No requiere entrada'), ('gratis', 'Gratis'), ('pagado', 'Pagado'), ('consultar', 'Consultar')], default='consultar', max_length=20),
        ),
    ]
