# Generated by Django 5.2.13 on 2026-09-04 20:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('establecimientos', '0009_recomendacionestablecimiento_plato_tipico'),
        ('turismo', '0006_alter_lugarturistico_tipo_costo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('establecimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='establecimientos.establecimiento')),
                ('lugar_turistico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='turismo.lugarturistico')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favorito',
                'verbose_name_plural': 'Favoritos',
                'ordering': ['-creado'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('establecimiento__isnull', False), ('lugar_turistico__isnull', True)), models.Q(('establecimiento__isnull', True), ('lugar_turistico__isnull', False)), _connector='OR'), name='favorito_un_solo_recurso'), models.UniqueConstraint(fields=('usuario', 'establecimiento'), name='unique_favorito_establecimiento'), models.UniqueConstraint(fields=('usuario', 'lugar_turistico'), name='unique_favorito_lugar')],
            },
        ),
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valoracion', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('comentario', models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(1000)])),
                ('estado', models.CharField(choices=[('publicado', 'Publicado'), ('oculto', 'Oculto')], default='publicado', max_length=20)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('establecimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to='establecimientos.establecimiento')),
                ('lugar_turistico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to='turismo.lugarturistico')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reseña',
                'verbose_name_plural': 'Reseñas',
                'ordering': ['-creado'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('establecimiento__isnull', False), ('lugar_turistico__isnull', True)), models.Q(('establecimiento__isnull', True), ('lugar_turistico__isnull', False)), _connector='OR'), name='resena_un_solo_recurso'), models.CheckConstraint(condition=models.Q(('valoracion__gte', 1), ('valoracion__lte', 5)), name='resena_valoracion_1_5'), models.UniqueConstraint(fields=('usuario', 'establecimiento'), name='unique_resena_establecimiento'), models.UniqueConstraint(fields=('usuario', 'lugar_turistico'), name='unique_resena_lugar')],
            },
        ),
    ]
