# Generated by Django 5.2.13 on 2026-08-14 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios_turista', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicioturista',
            name='embed_maps',
            field=models.TextField(blank=True, help_text="Pega aquí el código <iframe> completo que te da Google Maps en 'Compartir → Insertar un mapa'. Muestra el pin con el nombre real del servicio. Déjalo vacío si no aparece en Google Maps.", verbose_name='Código embed de Google Maps'),
        ),
        migrations.AddField(
            model_name='servicioturista',
            name='maps_url',
            field=models.TextField(blank=True, help_text="Pega aquí la URL de la ficha del negocio en Google Maps. Se usa para los botones 'Abrir mapa' y 'Cómo llegar'. Déjalo vacío si no aparece en Google Maps.", verbose_name='URL de la ficha en Google Maps'),
        ),
    ]
