# Generated by Django 5.2.13 on 2026-08-14 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios_turista', '0002_servicioturista_embed_maps_servicioturista_maps_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicioturista',
            name='embed_maps',
            field=models.TextField(blank=True, help_text="Pega aquí el código &lt;iframe&gt; completo que te da Google Maps en 'Compartir → Insertar un mapa'. Muestra el pin con el nombre real del servicio. Déjalo vacío si no aparece en Google Maps.", verbose_name='Código embed de Google Maps'),
        ),
    ]
