# Generated by Django 5.2.13 on 2026-08-17 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('establecimientos', '0008_alter_sucursalestablecimiento_maps_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaPlatoTipico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoría de plato típico',
                'verbose_name_plural': 'Categorías de platos típicos',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='PlatoEstablecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('establecimiento', models.ForeignKey(limit_choices_to={'tipo': 'restaurante'}, on_delete=django.db.models.deletion.CASCADE, related_name='platos_disponibles', to='establecimientos.establecimiento')),
            ],
            options={
                'verbose_name': 'Plato disponible en establecimiento',
                'verbose_name_plural': 'Platos disponibles en establecimientos',
                'ordering': ['establecimiento__nombre', 'plato__nombre'],
            },
        ),
        migrations.CreateModel(
            name='PlatoTipico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('descripcion_corta', models.CharField(blank=True, help_text='Descripción breve del plato. Evita párrafos largos.', max_length=255)),
                ('imagen', models.ImageField(blank=True, upload_to='gastronomia/platos/')),
                ('texto_alt_imagen', models.CharField(blank=True, max_length=180)),
                ('es_plato_bandera', models.BooleanField(default=False, help_text='Márcalo si es uno de los platos representativos de Huánuco.', verbose_name='Plato bandera')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='platos', to='gastronomia.categoriaplatotipico', verbose_name='Categoría')),
                ('establecimientos', models.ManyToManyField(blank=True, related_name='platos_tipicos', through='gastronomia.PlatoEstablecimiento', to='establecimientos.establecimiento')),
            ],
            options={
                'verbose_name': 'Plato típico',
                'verbose_name_plural': 'Platos típicos',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='platoestablecimiento',
            name='plato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidad', to='gastronomia.platotipico'),
        ),
        migrations.CreateModel(
            name='IngredienteClavePlato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('plato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes', to='gastronomia.platotipico')),
            ],
            options={
                'verbose_name': 'Ingrediente clave',
                'verbose_name_plural': 'Ingredientes clave',
                'ordering': ['plato__nombre', 'orden', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='platoestablecimiento',
            constraint=models.UniqueConstraint(fields=('plato', 'establecimiento'), name='unique_plato_por_establecimiento'),
        ),
        migrations.AddConstraint(
            model_name='ingredienteclaveplato',
            constraint=models.UniqueConstraint(fields=('plato', 'nombre'), name='unique_ingrediente_por_plato'),
        ),
    ]
