# Generated by Django 5.2.13 on 2026-07-25 17:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movilidad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsejoMovilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Consejo de movilidad',
                'verbose_name_plural': 'Consejos de movilidad',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TransportePublico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('nombre_alternativo', models.CharField(blank=True, max_length=100)),
                ('descripcion', models.CharField(max_length=255)),
                ('imagen', models.ImageField(blank=True, upload_to='movilidad/transportes/')),
                ('texto_alt_imagen', models.CharField(blank=True, max_length=180)),
                ('tarifa_minima', models.DecimalField(decimal_places=2, help_text='Precio mínimo referencial expresado en soles.', max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tarifa mínima referencial')),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Transporte público',
                'verbose_name_plural': 'Transportes públicos',
                'ordering': ['orden', 'nombre'],
            },
        ),
    ]
