# Generated by Django 5.2.13 on 2026-07-29 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movilidad', '0003_seed_transportes_consejos'),
    ]

    operations = [
        migrations.AddField(
            model_name='consejomovilidad',
            name='seccion',
            field=models.CharField(choices=[('tarifas_taxi', 'Transporte y tarifas'), ('como_llegar_terrestre', 'Cómo llegar — Vía terrestre'), ('como_llegar_aerea', 'Cómo llegar — Vía aérea')], db_index=True, default='tarifas_taxi', max_length=40),
        ),
        migrations.AddField(
            model_name='rutamovilidad',
            name='duracion_automovil',
            field=models.CharField(blank=True, help_text='Ejemplo: 8 horas y 30 minutos.', max_length=80),
        ),
        migrations.AddField(
            model_name='rutamovilidad',
            name='duracion_bus',
            field=models.CharField(blank=True, help_text='Ejemplo: 10 horas.', max_length=80),
        ),
        migrations.AddField(
            model_name='rutamovilidad',
            name='orden',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rutamovilidad',
            name='seccion',
            field=models.CharField(choices=[('general', 'General'), ('como_llegar', 'Cómo llegar')], db_index=True, default='general', max_length=30),
        ),
    ]
